### ISSUE TITLE
ctrl+shift+f9 selecting all occurrences of the text selected

### ISSUE THREAD

**Issue by Mashashi** [mikinw/StickySelection#20]
Hi mikinw,

First of all thank you for the great work. This is something that should be shipped on Intellij but unfortunately is not.

Now the thing is that when one makes a selection for a paint group with ctrl+shift+f9 all entries on the file that have this value let's say "3.0" are selected. This is undesirable in some circumstances. I would like to know if it is possible to only add the current marked entry instead of all which have the value "3.0" on the file.

Thank you in advance,
Mashashi

**Comment by Mashashi** [comment]
I believe I am using version v2.4 - 18-11-2017

**Comment by Piotruscik** [comment]
There is a little hacky way to do it. All occurrences are highlighted only if there is single caret. In case of two or more carets, only actually selected occurrences will be highlighted. So you can alt+click somewhere else to make a second caret before highlighting the selection.

**Comment by mikinw** [comment]
@Mashashi selecting all occurrences was the whole purpose of the plugin when I started, however I'll check if your request could easily be added (without hindering the usage of the other use cases)

**Comment by mikinw** [comment]
the feature is added in v3.1
