### ISSUE TITLE
If any Paint Group Shortcut Letter is removed in any Color Scheme, then the Settings are empty

### ISSUE THREAD

**Issue by schittli** [mikinw/StickySelection#21]
Good evening

**Thank you very much for this very useful Plugin!**, it's a shame that IntelliJ does not offer such basic functions itself.

#### There is a small bug:
1. In the Settings, remove one "Paint Group Shortcut" Letter (keep the textbox empty), save and close the Settings
2. Reopen the StickySelection Settings: it will be empty

Kind regards,
Thomas

**Comment by mikinw** [comment]
with the 3.0 release this should be fixed.
Please reopen it, if the problem still exists.
