### ISSUE TITLE
Paint group highlight layer is not saved to xml

### ISSUE THREAD

**Issue by Piotruscik** [mikinw/StickySelection#22]
Thank you for all your work, it's one of my favorite plugins and I use it a lot. But there is one rather minor, but quite annoying problem with it. If I set highlight layer on my paint group, it's not saved and resets to zero every time I restart the editor.
I have found it's caused by naming mismatch in getter and setter in model/PaintGroupDataBean.java (getHighlightLayer vs setLayer) - changing method name from setLayer to setHighlightLayer should fix it.

**Comment by mikinw** [comment]
Thank you, I'm glad someone finds it useful.
I've been busy with my job recently, but I'll have some free time to look at it in the coming weeks. Actually I've seen the bug also ;-) .

**Comment by mikinw** [comment]
with the 3.0 release this should be fixed.
Please reopen it, if the problem still exists.
