### ISSUE TITLE
Clear a single selection

### ISSUE THREAD

**Issue by PranayKarani** [mikinw/StickySelection#27]
Thanks for the plugin. Love it!
How can I clear a single selection? When I select 'clear' all the selections in the group are cleared. I just want to "un-highlight" just one highlighted selection text.

**Comment by mikinw** [comment]
Thank you for suggesting!
While it can be implemented, an it may be a good idea, but could you give me a real life example how can this be useful?

**Comment by mikinw** [comment]
the feature is added in v3.1
